# Simulation Configuration File

satellite:
      # Sensors
      cameras:
            [
                  {
                        "name": "x+",
                        # TODO: double check if the cameras are rotated by 180 degrees (i.e. we might get the images upside down as is)
                        "body_R_camera": [ [ 0,0,1 ], [ -1,0,0 ], [ 0,-1,0 ] ],  # rotation matrix representing a transformation from camera-frame to body-frame
                        "t_body_to_camera": [ 0.05116, -0.000198, -0.02927 ],  # m, position of camera in the satellite's body frame
                  },
                  {
                        "name": "y+",
                        "body_R_camera": [ [ 1,0,0 ], [ 0,0,1 ], [ 0,-1,0 ] ],
                        "t_body_to_camera": [ -0.00018, 0.051362, -0.02927 ],
                  },
                  {
                        "name": "x-",
                        "body_R_camera": [ [ 0,0,-1 ], [ 1,0,0 ], [ 0,-1,0 ] ],
                        "t_body_to_camera": [ -0.05214, 0.000022, -0.02927 ],
                  },
                  {
                        "name": "y-",
                        "body_R_camera": [ [ -1,0,0 ], [ 0,0,-1 ], [ 0,-1,0 ] ],
                        "t_body_to_camera": [ -0.00030, -0.051438, -0.02927 ],
                  },
            ]

vision:
      salient_mgrs_region_ids: [
            '10S', '10T', '11R', '12R', '16T', '17R', '17T', '18S',
            '32S', '32T', '33S', '33T', '52S', '53S', '54S', '54T'
      ]
