"""
This script is designed to run the EarthImageSimulator class and generate an image for a given spacecraft position, attitude and camera model.
It requires the following arguments:
    --name: Name of the experiment
    --meas_rate: Rate at which measurements should be taken

The script requires as input the spacecraft trajectory and attitude, which are generated by the run_dynamics script and should be stored as: 
- /output_dir
    - /experiment_name
        - ground_truth.npz
            - attitude
            - trajectory
            - daytime
        - args.json

The script will generate (append in the args.json case) the following contents in the output directory:
- /output_dir
    - /experiment_name
        -/images
            -/<timestep>
                - img_<timestep>_<camera_name>.png
                - lat_lon_<timestep>_<camera_name>.npy

        - args.json
"""
import argparse
import json
import os
from functools import partial
from multiprocessing import cpu_count, Pool

import brahe
import cv2
import numpy as np
from brahe.epoch import Epoch
from tqdm import tqdm

from image_simulation.earth_vis import EarthImageSimulator, GeoTIFFCache
from image_simulation.camera_model import CameraModelManager
from utils.brahe_utils import increment_epoch
from utils.config_utils import USER_CONFIG_PATH, load_config
from utils.function_utils import unpack_and_call


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the image simulator at periodic intervals along the saved trajectory.",
    )
    parser.add_argument(
        "--name",
        type=str,
        default="test",
        help="Name of the experiment",
    )
    parser.add_argument(
        "--meas_rate",
        type=int,
        default=120,
        help="Rate at which measurements should be taken",
    )
    parser.add_argument(
        "--skip_night",
        action="store_true",
        help="Whether to skip generating images that are over the dark half of the Earth.",
    )
    parser.add_argument(
        "--num_processes",
        type=int,
        default=int(0.8 * cpu_count()),
        help="Number of processes to use for image generation",
    )

    return parser.parse_args()


def generate_image(
    position: np.ndarray, attitude: np.ndarray, camera_name: str, index: int, output_dir: str
) -> None:
    """
    Generate an image and lat/lon .npy file for a given position, attitude, and camera model.

    :param position: The position of the spacecraft in ECEF coordinates.
    :param attitude: A numpy array of shape (3, 3) representing the rotation matrix from body to ECEF frame.
    :param camera_name: The name of the camera model to use.
    :param index: The index in the trajectory that the image corresponds to.
    :param output_dir: The directory to save the generated image.
    """
    earth_image_sim = EarthImageSimulator(
        geotiff_cache=GeoTIFFCache(max_cache_size=0),
        inpaint_blue_marble=True,
        blue_marble_month=None,
    )
    camera_model_manager = CameraModelManager()
    camera_model = camera_model_manager[camera_name]

    frame, lat_lon = earth_image_sim.simulate_image_for_training(position, attitude, camera_model)

    suffix = f"{index}_{camera_name}"
    cv2.imwrite(
        os.path.join(output_dir, str(index), f"img_{suffix}.png"),
        cv2.cvtColor(frame.image, cv2.COLOR_RGB2BGR),
    )
    np.save(
        os.path.join(output_dir, str(index), f"lat_lon_{suffix}.npy"),
        lat_lon,
    )


def image_vis(args: argparse.Namespace) -> None:
    """
    Visualize earth for a set of positions and attitudes using all available cameras.
    :param: args
    """
    output_dir = os.path.join(load_config(USER_CONFIG_PATH)["output_dir"], args.name)
    if (
        not os.path.exists(f"{output_dir}/ground_truth.npz")
    ):
        raise FileNotFoundError(
            f"One of the required files in {args.name} does not exist. Please run the trajectory generation script first."
        )
    data = np.load(f"{output_dir}/ground_truth.npz")
    trajectory_gt = data["trajectory"]
    attitude_gt = data["attitude"]
    daytime_gt = data["daytime"]

    try:
        with open(f"{output_dir}/args.json", "r") as jsonfile:
            arg_data = json.load(jsonfile)

    except Exception as e:
        raise ValueError(f"Error in args.json in {args.name}: {e}")

    # Check that if a name was provided it matches the one in the json file
    assert (
        arg_data["name"] == args.name
    ), f"Name in args.json does not match the provided name: {arg_data['name']} != {args.name}"

    # Store args as part of json
    arg_data["meas_rate"] = args.meas_rate
    arg_data["num_processes"] = args.num_processes

    with open(f"{output_dir}/args.json", "w") as jsonfile:
        json.dump(arg_data, jsonfile, indent=4)

    # Set the starting epoch and dt based on the args.json file
    starting_epoch = Epoch(*brahe.time.mjd_to_caldate(arg_data["start_date"]))
    dt = 1 / arg_data["frequency"]

    if not os.path.exists(f"{output_dir}/images"):
        os.makedirs(f"{output_dir}/images")

    requests = []
    for i, state in enumerate(trajectory_gt):
        # Only run the earth image visualizer if it's a measurement step and daytime
        if i % args.meas_rate == 0 and (not args.skip_night and daytime_gt[i]):
            
            # Get the current epoch and position in ECEF coordinates
            curr_epoch = increment_epoch(starting_epoch, i * dt)
            ecef_R_eci = brahe.frames.rECItoECEF(curr_epoch)
            position_ecef = ecef_R_eci @ state[0:3]
            
            # Create the directory for the current timestep images to be stored 
            os.makedirs(f"{output_dir}/images/{i}", exist_ok=True)

            for camera_name in CameraModelManager.CAMERA_NAMES:
                requests.append((position_ecef, attitude_gt[i], camera_name, i))

    func = partial(generate_image, output_dir=f"{output_dir}/images")
    with Pool(args.num_processes) as pool:
        list(
            tqdm(
                pool.imap_unordered(
                    partial(unpack_and_call, func),
                    requests,
                    chunksize=1,
                ),
                total=len(requests),
                desc="Generating images",
            )
        )


if __name__ == "__main__":
    image_vis(parse_args())
